// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBt8JfGKZH6i6boZ3r4Bn_cDq5fXbWIxE',
    appId: '1:875998543044:android:3dcc70fc4adc63102ddd91',
    messagingSenderId: '875998543044',
    projectId: 'houserental-29ec3',
    databaseURL: 'https://houserental-29ec3-default-rtdb.firebaseio.com',
    storageBucket: 'houserental-29ec3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0xnqGr89OUFMjNT-f8Jwz552SXkgViOw',
    appId: '1:875998543044:ios:b3065b593707ba392ddd91',
    messagingSenderId: '875998543044',
    projectId: 'houserental-29ec3',
    databaseURL: 'https://houserental-29ec3-default-rtdb.firebaseio.com',
    storageBucket: 'houserental-29ec3.appspot.com',
    iosBundleId: 'com.example.rentingApp',
  );
}
